#!/bin/bash
echo "🚂 Railway Setup für Ollama"
echo ""
echo "Bitte folgen Sie diesen Schritten:"
echo ""
echo "1. Gehen Sie zu https://railway.app"
echo "2. Erstellen Sie einen Account (mit GitHub)"
echo "3. Klicken Sie auf 'New Project' → 'Deploy from GitHub repo'"
echo "4. Wählen Sie Ihr Repository: BiGKerem/BeautyAI"
echo "5. Railway erkennt automatisch Dockerfile.ollama"
echo "6. Generieren Sie eine Domain in Settings → Networking"
echo "7. Öffnen Sie die Shell und führen Sie aus: ollama pull llama3.2"
echo "8. Kopieren Sie die Railway-URL"
echo "9. Setzen Sie in Vercel: OLLAMA_BASE_URL=https://your-railway-url.railway.app"
echo ""
echo "📖 Detaillierte Anleitung: RAILWAY_QUICKSTART.md"
